version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Optional if the file is named 'Dockerfile'
    ports:
      - "5500:5500"           # Map the container port to your host port
    env_file:
      - .env                   # Load environment variables from the .env file
    command: npm run server     # Command to start the application
